const RCP={
  'Adobo':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Adobo_Marinade.xlsx',
  'Arroz con Pollo':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Arroz_Con_Pollo_Main.xlsx',
  'Atakilt':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Atakilt_Wat_Vegan.xlsx',
  'Baked Tomato Fish':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Baked_Tomato_Fish_Main.xlsx',
  'Baked Tomato Spice':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Spice%20Mixes/Baked_Tomato_Fish_Spice.xlsx',
  'Baked Tomato Tofu':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Baked_Tomato_Tofu_Vegan.xlsx',
  'BBQ Chicken':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/BBQ_Chicken_Legs_Main.xlsx',
  'BBQ Sauce':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Honey_BBQ_Sauce.xlsx',
  'BBQ Seasoning':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Spice%20Mixes/BBQ_Spice.xlsx',
  'BBQ Vegan':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/BBQ_Chicken_Legs_Main.xlsx',
  'Beef & Vegetable Stew':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Beef_Stew.xlsx',
  'Beef Lasagna':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Beef_Lasagna_Sauce.xlsx',
  'Beef Nacho':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Beef_Nacho_Main.xlsx',
  'Beef Stew':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Beef_Stew.xlsx',
  'Berbere':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Berbere_Beef_Kebabs_Main.xlsx',
  'Berbere Spice':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Spice%20Mixes/Berbere_Spice.xlsx',
  'Black Bean Patt':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Kebabs_Vegan.xlsx',
  'Blackened Fish':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Blackened_Fish_Main.xlsx',
  'Blackened Spice':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Spice%20Mixes/Blackened_Spice.xlsx',
  'Blackened Tofu':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Blackened_Tofu_Vegan.xlsx',
  'Butter Chicken':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Butter_Chicken_Main.xlsx',
  'Butter Chickpeas':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Butter_Chickpeas_Vegan.xlsx',
  'Caribbean Chicken':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Caribbean_Curry_Chicken_Main.xlsx',
  'Caribbean Curry':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Caribbean_Curry_Chicken_Main.xlsx',
  'Caribbean Spice':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Spice%20Mixes/Caribbean_Curry_Spice.xlsx',
  'Caribbean Stew':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Caribbean_Sweet_Potato_Stew.xlsx',
  'Carnitas Sauce':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Carnitas_Sauce.xlsx',
  'Carnitas Spice':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Spice%20Mixes/Carnitas_Spice.xlsx',
  'Chicken Carnitas':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Chicken_Carnitas_Main.xlsx',
  'Chicken Griot':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Chicken_Griot_Main.xlsx',
  'Chicken Ranch':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Chicken_Ranch_Salad_Main.xlsx',
  'Chicken Vindaloo':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Vindaloo_Sauce.xlsx',
  'Chickpea Chili':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/White_Chicken_Chickpea_Chili_Stew.xlsx',
  'Chickpea Shakshuka':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Shakshuka_Vegan.xlsx',
  'Chimichurri':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Chimichurri_Marinade.xlsx',
  'Chow Mein':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Chicken_Mushroom_Fried_Rice_Main.xlsx',
  'Citrus Tofu':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Tofu_Griot_Vegan.xlsx',
  'CONC Salad':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Beef_CONC_Salad_Main.xlsx',
  'Coronation Chicken':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Chicken_Ranch_Salad_Main.xlsx',
  'Crispy Chicken Tender':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Oven_Fried_Chicken_Main.xlsx',
  'Curry House':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Spice%20Mixes/Curry_House_Spice.xlsx',
  'Curry Tofu':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Spice%20Mixes/Curry_Fish_Tofu_Spice.xlsx',
  'Eggplant':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Yetisse_Fish_Stew.xlsx',
  'Fajita':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Chicken_Fajitas_Main.xlsx',
  'Fajita Spice':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Spice%20Mixes/Fajita_Spice.xlsx',
  'Fish Curry':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Spice%20Mixes/Curry_Fish_Tofu_Spice.xlsx',
  'Five-Spice':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Five_Spice_Marinade.xlsx',
  'Fried Rice':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Chicken_Mushroom_Fried_Rice_Main.xlsx',
  'Garam Masala':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Spice%20Mixes/Garam_Masala_Spice.xlsx',
  'Glazed Chicken':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Glazed_Chicken_Pineapple_Main.xlsx',
  'Glazed Ham':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Glazed_Ham_Pineapple_Main.xlsx',
  'Glazed Tofu':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Glazed_Tofu_Pineapple_Vegan.xlsx',
  'Gomen Besiga':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Gomen_Be_Siga_Main.xlsx',
  'Green Curry':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Spice%20Mixes/Thai_Green_Curry_Paste_Spice.xlsx',
  'Green Seasoning':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Green_Seasoning_Marinade.xlsx',
  'Griot Marinade':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Griot_Marinade.xlsx',
  'Halal Beef Burger':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Halal_Chicken_Burgers_Main.xlsx',
  'Halal Breaded':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Halal_Chicken_Burgers_Main.xlsx',
  'Halal Chicken Burger':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Halal_Chicken_Burgers_Main.xlsx',
  'Halal Roast Chicken':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Herb_Chicken_Legs_Main.xlsx',
  'Herb Garlic':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Herb_Garlic_Potatoes_Side.xlsx',
  'Honey BBQ':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Potato_Salad_Side.xlsx',
  'Jerk Cauliflower':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Jerk_Cauliflower_Vegan.xlsx',
  'Jerk Chicken':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Jerk_Chicken_Legs_Main.xlsx',
  'Jerk Marinade':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Jerk_Marinade.xlsx',
  'Lime-Spiced Chicken':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Herb_Chicken_Legs_Main.xlsx',
  'Maple Glaze':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Maple_Glaze_Sauce.xlsx',
  'Marinade Five Spice':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Five_Spice_Marinade.xlsx',
  'Marinate Chicken Legs':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Jerk_Chicken_Legs_Main.xlsx',
  'Marinate Curry Fish':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Spice%20Mixes/Curry_Fish_Tofu_Spice.xlsx',
  'Mashed Potato':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Olive_Oil_Mash_Side.xlsx',
  'Massaman Curry':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Massaman_Beef_Curry_Stew.xlsx',
  'Massaman Paste':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Spice%20Mixes/Massaman_Curry_Paste_Spice.xlsx',
  'Meatball':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Meatballs_Main.xlsx',
  'Meatloaf':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Meatloaf_Main.xlsx',
  'Moroccan Chicken':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Moroccan_Chicken_Legs_Main.xlsx',
  'Moroccan Pork':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Moroccan_Pork_Main.xlsx',
  'Moroccan Rice':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Moroccan_Rice_Side.xlsx',
  'Moroccan Spice':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Spice%20Mixes/Moroccan_Spice.xlsx',
  'Moroccan Stew':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Moroccan_Stew_Vegan.xlsx',
  'Mushroom Stroganoff':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Mushroom_Stroganoff_Vegan.xlsx',
  'Nacho Spice':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Spice%20Mixes/Nacho_Spice.xlsx',
  'Oven Fried Chicken':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Oven_Fried_Chicken_Main.xlsx',
  'Pasta Primavera':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Pasta_Primavera_Stew.xlsx',
  'Peanut':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/African_Peanut_Chicken_Stew.xlsx',
  'Philly Steak':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Sliced_Sandwich_Beef_Main.xlsx',
  'Pork Carnitas':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Pork_Carnitas_Main.xlsx',
  'Pork Griot':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Pork_Griot_Main.xlsx',
  'Pork Vindaloo':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Vindaloo_Sauce.xlsx',
  'Portobello':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Mushroom_Sandwich_Vegan.xlsx',
  'Potato Salad':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Potato_Salad_Side.xlsx',
  'Potato Wedge':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Herb_Garlic_Potatoes_Side.xlsx',
  'Prep Griot':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Griot_Marinade.xlsx',
  'Quinoa':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Kebabs_Vegan.xlsx',
  'Refried Beans':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Arroz_Con_Pollo_Main.xlsx',
  'Roast Chicken':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Herb_Chicken_Legs_Main.xlsx',
  'Roasted Potato':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Herb_Garlic_Potatoes_Side.xlsx',
  'Sausage & Greens':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Sausage_Greens_Pasta_Main.xlsx',
  'Sausage & Veg':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Sausage_Greens_Pasta_Main.xlsx',
  'Sausage/Vegan':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Sausage_Greens_Pasta_Main.xlsx',
  'Season Carnitas':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Carnitas_Sauce.xlsx',
  'Sesame Chicken':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Sesame_Chicken_Main.xlsx',
  'Shakshuka':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Shakshuka_Vegan.xlsx',
  'Sliced Beef':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Sliced_Sandwich_Beef_Main.xlsx',
  'Spiced Tofu':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Yetisse_Fish_Stew.xlsx',
  'Spring Roll':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Chicken_Mushroom_Fried_Rice_Main.xlsx',
  'Stroganoff':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Beef_Stroganoff_Main.xlsx',
  'Sweet Potato Biscuit':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Sweet_Potato_Biscuits_Baking.xlsx',
  'Tandoori':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Tandoori_Marinade.xlsx',
  'Teriyaki Chicken':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Teriyaki_Chicken_Legs_Main.xlsx',
  'Teriyaki Tofu':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Teriyaki_Tofu_Vegan.xlsx',
  'Thai Green Curry':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Spice%20Mixes/Thai_Green_Curry_Paste_Spice.xlsx',
  'Thai Green Curry Veg':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Thai_Green_Curry_Vegan.xlsx',
  'Tofu Griot':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Tofu_Griot_Vegan.xlsx',
  'Tomato Sauce':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Simple_Tomato_Sauce.xlsx',
  'Tuna Rex Salad':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Chicken_Ranch_Salad_Main.xlsx',
  'Tuna Salad':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Chicken_Ranch_Salad_Main.xlsx',
  'Veg Carnitas':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Carnitas_Vegan.xlsx',
  'Vegan Carnitas':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Carnitas_Vegan.xlsx',
  'Vegan Chili':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Chili_Vegan.xlsx',
  'Vegan Chilli':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Chili_Vegan.xlsx',
  'Vegan CONC':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/CONC_Salad_Vegan.xlsx',
  'Vegan Fajita':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Fajitas_Vegan.xlsx',
  'Vegan Gomen':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Gomen_Be_Siga_Vegan.xlsx',
  'Vegan Lasagna':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Vegan_Lasagna_Sauce.xlsx',
  'Vegan Mac':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Mac_and_Cheese_Vegan.xlsx',
  'Vegan Meatball':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Meatballs_Vegan.xlsx',
  'Vegan Meatloaf':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Meatloaf_Vegan.xlsx',
  'Vegan Mushroom Sandwich':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Mushroom_Sandwich_Vegan.xlsx',
  'Vegan Nacho':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Nacho_Vegan.xlsx',
  'Vegan Pot Pie':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Stew_Vegan.xlsx',
  'Vegan Sesame':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Sesame_Chikn_Vegan.xlsx',
  'Vegan Stew':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Stew_Vegan.xlsx',
  'Vegan Taco':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Taco_Al_Pastor_Vegan.xlsx',
  'Vegan Tender':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Oven_Fried_Chicken_Main.xlsx',
  'Vegan Vindaloo':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Vindaloo_Vegan.xlsx',
  'Vindaloo Marinade':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Vindaloo_Marinade.xlsx',
  'Vindaloo Sauce':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Vindaloo_Sauce.xlsx',
  'Vindaloo Spice':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Spice%20Mixes/Vindaloo_Spice.xlsx',
  'White Chicken Chili':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/White_Chicken_Chickpea_Chili_Stew.xlsx',
  'White Chilli':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/White_Chicken_Chickpea_Chili_Stew.xlsx',
  'Yetisse Fish':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Yetisse_Fish_Stew.xlsx',
  'Yetisse Spice':'https://conctoronto.sharepoint.com/sites/Kitchen/Shared%20Documents/Bloor/Recipes/Spice%20Mixes/Yetisse_Spice.xlsx'
}
const RCP_KEYS=Object.keys(RCP).sort((a,b)=>b.length-a.length);

function rcpUrl(name){for(const k of RCP_KEYS){if(name.includes(k))return RCP[k]}return null}